### ISSUE TITLE
Minecraft freeze, doesnt crash

### ISSUE THREAD

**Issue by BizareCarnival24** [glowing-octo-minecraft/issue-tracking#1]
when the freeze occurs, 2 cores of my cpu start using 100% of their capabilities and it will switch between cores. in the picture i opened up a chest it froze displaying both CPU0 and CPU2 running at 100%
![glowingoctominecraft_freeze](https://cloud.githubusercontent.com/assets/8552454/4113084/b3c7676c-3243-11e4-9a0d-2faf27a5e669.png)

**Comment by skwerlman** [comment]
Seems to have fixed itself; closing for now. If it reoccurs, let me know.
